### ISSUE TITLE
Fails to remove fence if tag is indented

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-md2html#1]
So this works:

    <md>
      ```html
      Unmarked title
      <div>Content</div>
      More content
      ```
    </md>

Result:

    <pre><code class="language-html">  Unmarked title
      &lt;div&gt;Content&lt;/div&gt;
      More content</code></pre>

But if your `<md>` tag is nested, it'll fail:

    <div>
      <md>
        ```html
        Unmarked title
        <div>Content</div>
        More content
        ```
      </md>
    </div>

Result:

    <pre><code>```html
    Unmarked title
    &lt;div&gt;Content&lt;/div&gt;
    More content
    ```</code></pre>

**Comment by Scrum** [comment]
@cossssmin publish v0.0.1

**Comment by cossssmin** [comment]
Awesome, that works well! There's just one more thing I noticed, I'll open a separate issue. Thanks!
