### ISSUE TITLE
Indentation turns everything into code blocks

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-md2html#3]
Given this:

```html
<div>
  <h2>Following, some markdown:</h2>
  <md>
    Lorem ipsum.
  </md>
</div>
```

With `v0.0.1` I now get this:

```html
<div>
    <h2>Following, some markdown:</h2>
    <pre><code>Lorem ipsum.</code></pre>
  </div>
```

The issue is with the indentation inside a markdown block - above there are 4 spaces before 'Lorem...' and as we know that signals a code block in markdown. 

If I use just two spaces, like this:

```html
<div>
  <h2>Following, some markdown:</h2>
  <md>
  Lorem ipsum.
  </md>
</div>
```

... I get this:

```html
<div>
    <h2>Following, some markdown:</h2>
    <p> Lorem ipsum.</p>
  </div>
```

Notice the space before Lorem.

Now, if I write _this_:

```html
<div>
  <h2>Following, some markdown:</h2>
  <md>
Lorem ipsum.
  </md>
</div>
```

... it finally works properly:

```html
<div>
    <h2>Following, some markdown:</h2>
    <p>Lorem ipsum.</p>
  </div>
```

I understand this was the reason why the other Markdown plugins were doing complicated stuff with unindenting and reindenting the text - if you have a `<md>` nested in your HTML, it's almost sure to be indented, and Markdown will treat it as a code block.

**Comment by Scrum** [comment]
@cossssmin try in v0.0.2

**Comment by cossssmin** [comment]
The `<code>` issue is resolved, thanks! 

It's still adding indentation though, so just as in the tests, this:

```html
<md>
  Lorem ipsum.
</md>
```

results in:

```html
<p>  Lorem ipsum.</p>
```

Which I guess is not a big issue in general, but working with fenced code is also affected.

So now this:

```html
    <md>
    ```html
    Unmarked title
      <div>Content</div>
    More content
    ```
    </md>
```

results in:

```html
<pre><code class="language-html">    Unmarked title
      &lt;div&gt;Content&lt;/div&gt;
    More content</code></pre>
```

Which will render like this:

<pre><code class="language-html">    Unmarked title
      &lt;div&gt;Content&lt;/div&gt;
    More content</code></pre>

So although the word "Unmarked" has the same indentation in the HTML as the `<md>` tag and the fence above it, it still gets one level of indentation. Looks to me like code blocks start with 0 indentation: the example above is indented with 2 spaces, so that's why the code block also gets 2 spaces, even though it is on the same level as the `<md>` tag.

This means that inside nested markup I need to do something like this to properly output code blocks:

```html
<div>
  <div>
    <md>
    ```html
Unmarked title
  <div>Content</div>
More content
    ```
    </md>
  </div>
</div>
```

Makes sense?

**Comment by Scrum** [comment]
It is difficult to understand how the author wanted to design his block of code, we also don’t know what indentation of the tag

**Comment by Scrum** [comment]
maybe you should think about a parameter that will indicate something like that

**Comment by Scrum** [comment]
or take a level, but then we have to go through the whole tree independently, is there a tag there or not

**Comment by cossssmin** [comment]
Yeah, I guess that's why the other markdown plugins have that complicated setup. Again, it's not a huge issue, it can be easily fixed by manually unindenting the code block.

Thanks again!
